version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-3 | docker login --username AWS --password-stdin 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t g2-userprofile-cp:userprofile .
      - docker tag g2-userprofile-cp:userprofile 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2-userprofile-cp:userprofile
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2-userprofile-cp:userprofile
      - echo Writing image definitions file...
      - printf '[{"name":"userprofile-container","imageUri":"%s"}]' 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g2-userprofile-cp:userprofile > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json